{% set version = "0.9" %}

package:
  name: pygeos
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pygeos/pygeos-{{ version }}.tar.gz
  sha256: c0584b20e95f80ee57277a6eb1e5d7f86600f8b1ef3c627d238e243afdcc0cc7

build:
  number: 3
  skip: true  # [py2k]
  script:
    - set GEOS_INCLUDE_PATH=%LIBRARY_INC%  # [win]
    - set GEOS_LIBRARY_PATH=%LIBRARY_LIB%  # [win]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy
    - geos
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - geos

test:
  imports:
    - pygeos

about:
  home: https://github.com/caspervdw/pygeos
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Wraps GEOS geometry functions in numpy ufuncs

  description: |
    PyGEOS is a C/Python library with vectorized geometry functions.
    The geometry operations are done in the open-source geometry library GEOS.
    PyGEOS wraps these operations in NumPy ufuncs providing a performance
    improvement when operating on arrays of geometries.
  doc_url: https://pygeos.readthedocs.io/en/latest/
  dev_url: https://github.com/caspervdw/pygeos

extra:
  recipe-maintainers:
    - caspervdw
    - jorisvandenbossche
