{% set version = "0.12.0" %}

package:
  name: pygeos
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pygeos/pygeos-{{ version }}.tar.gz
  sha256: 3c41542ef67c66015f443ae3e6e683503a8a221f9c24fb2380f6ae42aed1600a

build:
  number: 1
  skip: true  # [py2k]
  script:
    - set GEOS_INCLUDE_PATH=%LIBRARY_INC%  # [win]
    - set GEOS_LIBRARY_PATH=%LIBRARY_LIB%  # [win]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy
    - geos
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - geos

test:
  requires:
    - pytest
  commands:
    - pytest --pyargs pygeos.tests

about:
  home: https://github.com/pygeos/pygeos
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: GEOS wrapped in numpy ufuncs

  description: |
    PyGEOS is a C/Python library with vectorized geometry functions.
    The geometry operations are done in the open-source geometry library GEOS.
    PyGEOS wraps these operations in NumPy ufuncs providing a performance
    improvement when operating on arrays of geometries.
  doc_url: https://pygeos.readthedocs.io/
  dev_url: https://github.com/pygeos/pygeos

extra:
  recipe-maintainers:
    - caspervdw
    - jorisvandenbossche
