{% set version = "0.14" %}

package:
  name: pygeos
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pygeos/pygeos-{{ version }}.tar.gz
  sha256: 30fbc17f64844200b85133b885fcfb65541b8779531f6ef4f8fe467d3fba7623

build:
  number: 2
  skip: true  # [py2k]
  script:
    - set GEOS_INCLUDE_PATH=%LIBRARY_INC%  # [win]
    - set GEOS_LIBRARY_PATH=%LIBRARY_LIB%  # [win]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy
    - geos
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - geos

test:
  requires:
    - pytest
  commands:
    # skip offset_curve tests for GEOS 3.11.0
    - pytest --pyargs pygeos.tests -k "not offset_curve"

about:
  home: https://github.com/pygeos/pygeos
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: GEOS wrapped in numpy ufuncs

  description: |
    PyGEOS is a C/Python library with vectorized geometry functions.
    The geometry operations are done in the open-source geometry library GEOS.
    PyGEOS wraps these operations in NumPy ufuncs providing a performance
    improvement when operating on arrays of geometries.
  doc_url: https://pygeos.readthedocs.io/
  dev_url: https://github.com/pygeos/pygeos

extra:
  recipe-maintainers:
    - caspervdw
    - jorisvandenbossche
