{% set version = "0.3" %}

package:
  name: pygeos
  version: {{ version }}

source:
  git_url: https://github.com/caspervdw/pygeos
  branch: master

build:
  number: 0
  skip: True  # [py2k]
  script:
    - set GEOS_INCLUDE_PATH=%LIBRARY_INC%  # [win]
    - set GEOS_LIBRARY_PATH=%LIBRARY_LIB%  # [win]
    - "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - geos
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - geos

test:
  imports:
    - pygeos

about:
  home: https://github.com/caspervdw/pygeos
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Wraps GEOS geometry functions in numpy ufuncs'

  description: |
    PyGEOS is a C/Python library with vectorized geometry functions.
    The geometry operations are done in the open-source geometry library GEOS.
    PyGEOS wraps these operations in NumPy ufuncs providing a performance
    improvement when operating on arrays of geometries.
  doc_url: https://pygeos.readthedocs.io/en/latest/
  dev_url: https://github.com/caspervdw/pygeos

extra:
  recipe-maintainers:
    - caspervdw
    - jorisvandenbossche
